name: Update Azure JSON
on: workflow_dispatch 
  #schedule:
    #- cron: '59 23 * * *'

permissions:
  contents: write
  
jobs:
    build:
      name: Run PowerShell Script
      runs-on: windows-latest
      steps:

        - uses: actions/checkout@v3
        - name: Script
          shell: pwsh
          env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
            TENANT_ID: ${{ secrets.TENANT_ID }}
          run: ./create-azurejson.ps1
